### ISSUE TITLE
Popups don't stay open on Ubuntu+Compiz

### ISSUE THREAD

**Issue by themightychris** [deanoemcke/spaces#1]
The move-to-space and quick find popups flash open momentarily but disappear before they can be interacted with

**Comment by jmason888** [comment]
I've had this problem on ChromeOS too:
```
Version:   Version 64.0.3270.0 (Official Build) dev (64-bit)
Platform:  10134.0.0 (Official Build) dev-channel gandof
Firmware:  Google_Gandof.6301.155.9
```
Exactly as above, the popup opens, but clicking in it dismisses the popup without doing anything. 

[Bao Ho](https://plus.google.com/102553037065128878831) posted a patch to the [support pages](https://chrome.google.com/webstore/detail/spaces/cenkmofngpohdnkbjdpilgpmbiiljjim/support) (Apr 22, 2016, "_Solution for the problem of space switch in linux_", currently #37) which solves the problem for me. It adds the following after at line 77 of [background.js](https://github.com/deanoemcke/spaces/blob/master/js/background.js):
```
if (windowId == chrome.windows.WINDOW_ID_NONE || windowId == spacesPopupWindowId) {
    return;
}
```

**Comment by jmason888** [comment]
See PR #2.

Thank you @deanoemcke for the extension (and for open-sourcing it), and thank you @tri-bao for the patch.

**Comment by themightychris** [comment]
I can confirm this fix works for me!
