### ISSUE TITLE
Feature Request: Fuzzy Search when typing space names to switch

### ISSUE THREAD

**Issue by starpause** [deanoemcke/spaces#10]
Example Fuzzy Search javascript implementations 

https://github.com/bevacqua/fuzzysearch
https://github.com/krisk/Fuse

Thanks for the awesome extension!

**Comment by alankyshum** [comment]
Wow, thanks for suggesting the feature. I was thinking about the same thing, and fuzzy search looks promising.

**Comment by deanoemcke** [comment]
Fixed in v1.1.0
