### ISSUE TITLE
Update chrome store version

### ISSUE THREAD

**Issue by themightychris** [deanoemcke/spaces#13]
Could you push an update to the chrome store?

**Comment by kirill-konshin** [comment]
+1

**Comment by deanoemcke** [comment]
I will try to work on this soon. There's a couple of bugs I'd love to fix on this project.

**Comment by ReActiveMicro** [comment]
I'm going to hire someone on Freelancer to address some issues and make things more useable.  I'll have the code branched here for review and approval.  Assuming all is good then you can publish it.

It's a good extension and very useful.  Just needs some bugs worked out.  Get in touch with me anytime.  Thx!

**Comment by deanoemcke** [comment]
@ReActiveMicro as mentioned in my email to you, it would be great if the code changes could be pushed here on gitHub as a new pull request.
Thanks!

**Comment by ReActiveMicro** [comment]
Hello Dean.

I believe the programmer will be uploading the changes soon.  In the
meantime I have attached the current build for your review.  New features
was to fix the names so they stay as ordered, and can be moved and set as
desired.  Drag and drop to order.
Download:
https://expirebox.com/download/d67f8b7e6fec7c1900ba81dd9497c5eb.html

Now I can edit the names with the edit icon next to them on the Space menu
button.

There's an option to enable or disable closing of all session windows on
"Go to main" menu.  This helps with massive amounts of tabs.  It can allow
for less resources used by Chrome as the cost of loading speed when
switching.  Or cost more resources like RAM but with better speed when
switching.  I found less RAM and less speed was the best solution for me
and all my tabs.

Pinned tabs now follow me from session window to session window.  And I can
set their order, which only changes if I change it.  This is nice as pinned
tabs can be things like gmail or common sites which are used from all
session windows.

Anyway, hope these fixes help.  Please review and send the update to the
Chrome Store.  I'd love to "officially" install.  And credit to
ReActiveMicro.com for the help or changes would be appreciated.

Thanks!


PS - I'm not sure if you did mention in your description or not, but this
extension works a lot like Firefox's "Group Tabs" used to.  A lot of us
found that useful, and this was the best alternative for Chrome I have
found to date.  The fancy graphical groups menu to switch and organize
sessions would be nice.  However a working extension is better than looks
anyway.



Henry S. Courbis

Office Toll Free: (800) REACTIVE (732-2848)
Office/Mobile Direct: (856) 779-1900
www.ReActiveMicro.com <http://www.ReactiveMicro.com> - Sales, Support, and
News, Our Headquarters on the Internet
ReActiveMicro.com/wiki  - Support, Software, Manuals, and History. Create
your own page today!
Facebook.com/reactivemicrousa - Our Social Media Outlet and Support

**Comment by themightychris** [comment]
Hi @ReActiveMicro , thanks for your work on Spaces!

From my own perspective only as another dedicated user, I don't want pinned tabs to be outside the save/restore of sessions. I have pinned tabs that are part of each saved space and it is important to me that pinned tabs stay inside the spaces flow. This behavior difference is the primary thing keeping me from using [Workona](https://workona.com/). My workflow is to keep a set of projects open in spaces on different desktops, rather than switching between spaces within one window. If you haven't seen Workona before, check it out -- it sounds like it might already be a better implementation of what you're looking for. If you want to bring this behavior to Spaces, please consider making it an option that can be turned on so that folks relying on the existing behavior like me don't have our workflow broken upon updating

**Comment by ReActiveMicro** [comment]
Hello Chris.

Thanks for the lead on Workona.  I'll give this a try and see how it goes.

Feel free to use and edit the existing code as you see fit.  Adding a menu
item to turn something on or off should be simple enough I would imagine.



Henry S. Courbis

Office Toll Free: (800) REACTIVE (732-2848)
Office/Mobile Direct: (856) 779-1900
www.ReActiveMicro.com <http://www.ReactiveMicro.com> - Sales, Support, and
News, Our Headquarters on the Internet
ReActiveMicro.com/wiki  - Support, Software, Manuals, and History. Create
your own page today!
Facebook.com/reactivemicrousa - Our Social Media Outlet and Support

**Comment by themightychris** [comment]
@ReActiveMicro do you still expect to be able to upload the source code for that build? I'd love to get to see a PR for the work and maybe poke around at it a bit myself

**Comment by ReActiveMicro** [comment]
Hey Chris.

I'll pester them again.  And why I sent the files I had.  With some luck
they will do it this weekend.  If not, check back with me and I'll keep
pestering them till it's done.

Sorry about the wait.



Henry S. Courbis

Office Toll Free: (800) REACTIVE (732-2848)
Office/Mobile Direct: (856) 779-1900
www.ReActiveMicro.com <http://www.ReactiveMicro.com> - Sales, Support, and
News, Our Headquarters on the Internet
ReActiveMicro.com/wiki  - Support, Software, Manuals, and History. Create
your own page today!
Facebook.com/reactivemicrousa - Our Social Media Outlet and Support

**Comment by deanoemcke** [comment]
@ReActiveMicro It's very important that all code changes get reviewed before they are incorporated into the extension. This is not just to make sure that the new code does not contain any bugs. Perhaps even more importantly, as @themightychris has demonstrated, we need to make sure that any new features and design changes are the best choice for the majority of users. 

There are always niche features that a single user may wish to have implemented, but if the feature is not wanted by the majority of other users then I prefer NOT to implement it, as adding too many of these sorts of features tends to lead to an extension that is complicated to understand and use.

**Comment by themightychris** [comment]
@deanoemcke could we return to the original request in this issue? The current code on github already fixes a number of issues that the current Chrome store version has. I'm referring people to this extension constantly and it sucks having to qualify with how to load an unpacked extension from GitHub. Is there much tech debt in the build->ship process or shortcomings in how extension updates work that would make shipping multiple patch updates in relatively short succession best to avoid?

@ReActiveMicro please open a separate pull request with your new code once you are able to, I'd like to keep this issue focused on clearing the minimal number of hurdles to just getting the current latest codebase shipped to the Chrome extensions store. I'm really looking forward to helping review and polish the work you've contributed, but since it's a bigger update than just bug fixes that could accelerate this release we should split up and parallelize the threads.

**Comment by Thovthe** [comment]
Prod prod.

**Comment by BlkPingu** [comment]
Any news on this?

**Comment by deanoemcke** [comment]
@themightychris I've just pushed v0.23 to the webstore. I'm really sorry I haven't done this sooner. 

@ReActiveMicro Any chance you could send me another link to the custom code you had produced? I could look at putting it into a PR if the original author does not want to. Thanks :)

**Comment by themightychris** [comment]
thanks @deanoemcke!

No worries, I got a pile of PRs languishing in my own repos, your time is much appreciated!

**Comment by faultylee** [comment]
Chromium decided to disable Spaces by default, ask to confirm the "Read and change your browsing history" permission. I was worried for a while as I saw the last code change here was 10 months ago. I thought someone high jacked your webstore account until I found this thread. 
Might be good to put a note in the webstore and maybe here on the readme.

**Comment by ReActiveMicro** [comment]
Hello Dean.

Current project: https://ufile.io/k7qhg

It worked, however I don't use it.  I think you recommended Workona?  It
does everything I need to do.  They don't seem to support pinned tabs
however.  So there is that issue.  But the work around is making them
"Resources".  It also doesn't like multi windows open at once.  But it's
simple and nothing to integrate.

Hope that helps!



Henry S. Courbis

Office Toll Free: (800) REACTIVE (732-2848)
Office/Mobile Direct: (856) 779-1900
www.ReActiveMicro.com <http://www.ReactiveMicro.com> - Sales, Support, and
News, Our Headquarters on the Internet
ReActiveMicro.com/wiki  - Support, Software, Manuals, and History. Create
your own page today!
Facebook.com/reactivemicrousa - Our Social Media Outlet and Support
