### ISSUE TITLE
Unable to name / rename space

### ISSUE THREAD

**Issue by BlkPingu** [deanoemcke/spaces#16]
Sometimes when renaming a space, it's possible to enter a name, but the name is not getting finalised. 
It just keeps accepting text and isn't renaming the space. 
Possibly the button for finalising the space is just non-reactive for some reason.
Is there a regex for possible names that could trigger this? I notices it doesn't always like all caps names.

I'll add a short video when I manage to reproduce the bug.

**Comment by Alexey-Panov** [comment]
I think my problem is similar. When finish type space name hit ENTER key and click outside of Spaces popup. And in name of space in popup didn't changed. Need to click inside popup and outside of text-field to save.

OK button near field will be ok =)

Thx for extensions btw

**Comment by deanoemcke** [comment]
Fixed in v1.1.1
