### ISSUE TITLE
The quick switch window does not offer the whole list of spaces

### ISSUE THREAD

**Issue by crguezl** [deanoemcke/spaces#18]
The **quick switch window** does not offer the whole list of *spaces*. Still you can recover the *lost* spaces using the **search** feature

**Comment by Thovthe** [comment]
I don't believe that the quick switch is supposed to have all of the spaces listed, that list could get quite long.  Since something similar has been mentioned in #6 before maybe the number should be increased?

**Comment by deanoemcke** [comment]
Fixed in v1.1.0
