### ISSUE TITLE
All my spaces lost - I have a json backup but it isn't restoring it

### ISSUE THREAD

**Issue by nahall** [deanoemcke/spaces#25]
I was using a local copy of spaces that I took from github a few months ago. There was a branch called "improve-export" I believe, and the manifest shows it is version 0.25.

I saw that version 1.1.1 had been released and saw that the chrome store has that version so I decided to remove the manually installed extension from chrome and load the store one instead so it would automatically upgrade.

When I had it back up, all my saved spaces were gone.

Fortunately I did a backup right before I installed the upgrade. But when I paste the json file into the spaces importer, it only imports 9 of the windows (there are 70+ windows in the json).

When I look at the json file, it seems like the file seems OK. But it is not importing it properly. Any suggestions on how to debug this?

**Comment by deanoemcke** [comment]
hmm.. any chance you'd want to share the json file with me?
i'm actually just about to push a new release with an import bug fix (not related to yours i suspect). would be great to resolve this at the same time!

**Comment by deanoemcke** [comment]
@nahall I have just pushed some bug fixes to master. Can you try installing from source again and see if your import works now?

**Comment by nahall** [comment]
Good timing! I used the master and it seems to have fixed the bug as it seems like the spaces were imported OK. Thanks.
