### ISSUE TITLE
Transferring spaces from chrome store version

### ISSUE THREAD

**Issue by themightychris** [deanoemcke/spaces#4]
I just installed the latest version from GitHub. I notice it has a new backup all spaces button, but my chrome still version is still installed too, has all my spaces, and has no such button. Is there a way to go under the hook and `cp` some data files around to migrate all my spaces to the github build?

**Comment by deanoemcke** [comment]
it might be possible. i'm not sure.
the extension uses an indexedDb database to store the spaces, it might be a simple as copying that indexedDb file across from one extension directory into the other?

would be keen to hear if you have any success with this.

alternatively, you could use something like session buddy to export each space. but that would involve you opening each one up :/

**Comment by themightychris** [comment]
I have both running in chrome at once, maybe I could inspect both and string together some sort of dump/load in my console with `copy(JSON.stringify(...))`

I'll try to dig in at some point, any clues you might lend to help me find the right part would be appreciated!

**Comment by themightychris** [comment]
nooooo after chrome updated last night the chrome store version got marked as "possibly corrupted" and the repair button worked but blew out all my spaces :'(

**Comment by deanoemcke** [comment]
oh god. i'm so sorry.
had you modified some of the files in the extension directory? I've never had an extension corrupt before.
are you on osx? if so, you might have an old version of your indexedDb database file in your timemachine?

the files should be in a folder something like `/Users/xxx/Library/Application Support/Google/Chrome/Profile.../`
doing a filesearch (with spotlight) for `nlnolkpmalnodndkndgjjehgmkepgdjn` is sometimes easier too. that is the extension id of the webstore version.

if you manage to get something back, i'll try to help you with exporting your sessions.

**Comment by themightychris** [comment]
Thanks! This was on an OSX box where I hadn't messed with extensions at all, I was just using the version from the chrome web store. After chrome restarted for an update that introduced a new extensions manager UI, Spaces was corrupt. No time machine backups unfortunately but I'll dig around.

I should mention I run Canary as my main browser soooo that's probably my fault

**Comment by themightychris** [comment]
I suppose this issue becomes a moot point once a version with the new "backup all spaces" feature ships to the webstore, that will enable existing users to export their spaces and from then on it will be easy to switch between the webstore version and github builds
