### ISSUE TITLE
Quick Switch PopUp only shows limited amount of windows

### ISSUE THREAD

**Issue by gxagxagx** [deanoemcke/spaces#6]
Currently the Quick Switch PopUp only shows 8 windows for me, scrolling does not work. 
It would be great if I can find all windows in the pop up thanks!!

**Comment by Thovthe** [comment]
Judging by this and #12 the quick switch UI could potentially use a little bit of a rethink.

**Comment by deanoemcke** [comment]
Fixed in v1.1.0
