### ISSUE TITLE
Really need a license...

### ISSUE THREAD

**Issue by JayGoldberg** [deanoemcke/spaces#7]
I'd like to fork this to fix some bugs but am concerned about the licensing. Can we just make it MIT or Apache?

**Comment by deanoemcke** [comment]
You want to make a PR?

**Comment by JayGoldberg** [comment]
Create 0a74985cae5281f8d786182a1af03665234fd526

**Comment by deanoemcke** [comment]
haha. gosh, i'm sorry. 
i meant, are you wanting to fork so that you can submit a PR for some improvements?
i'm happy to provide a license. but it would be nice if your improvements were submitted into this project as PR's so that we can get them into an official release..

**Comment by JayGoldberg** [comment]
Yes, I'd like to at least poke around with the idea of improvements and bugfixes. I'm on ChromeOS and having a hell of a time using the built-in window manager.

I'm evaluating a few projects to add fixes/features to, including https://github.com/EduCampi/chromewm.

The issue is I want to be sure that the code I submit will be under copyleft  so anyone can use it. Not so interested in contributing code to a codebase that may be converted to a commercial license.

**Comment by deanoemcke** [comment]
License added.
